// src/sql/base/browser/ui/checkbox/checkbox.component.ts
/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the Source EULA. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import {
	Component, Inject, forwardRef, ElementRef, OnInit, Input,
	Output, OnChanges, SimpleChanges, EventEmitter
} from '@angular/core';

import { Checkbox as sqlCheckbox } from 'sql/base/browser/ui/checkbox/checkbox';

@Component({
	selector: 'checkbox',
	template: ''
})
export class Checkbox implements OnInit, OnChanges {
	@Input() label!: string;
	@Input() enabled = true;
	@Input() checked = true;
	@Input('aria-label') private ariaLabel?: string;

	@Output() onChange = new EventEmitter<boolean>();

	private _checkbox?: sqlCheckbox;

	constructor(
		@Inject(forwardRef(() => ElementRef)) private _el: ElementRef
	) { }

	ngOnInit(): void {
		this._checkbox = new sqlCheckbox(this._el.nativeElement, {
			label: this.label,
			ariaLabel: this.ariaLabel || this.label,
			checked: this.checked,
			enabled: this.enabled
		});
		this._checkbox.onChange(e => { this.onChange.emit(e); });
	}

	ngOnChanges(changes: SimpleChanges): void {
		if (this._checkbox) {
			if (changes['label']) {
				this._checkbox.label = changes['label'].currentValue;
			}

			if (changes['enabled']) {
				this._checkbox.enabled = changes['enabled'].currentValue;
			}

			if (changes['checked']) {
				this._checkbox.checked = changes['checked'].currentValue;
			}
		}
	}
}

// src/sql/base/browser/ui/checkbox/checkbox.tsx
/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the Source EULA. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import 'vs/css!./media/checkbox';

import { Color } from 'vs/base/common/color';
import { Event, Emitter } from 'vs/base/common/event';
import { KeyCode } from 'vs/base/common/keyCodes';
import { Widget } from 'vs/base/browser/ui/widget';
import { $ } from 'vs/base/browser/dom';

export interface ICheckboxOptions {
	label: string;
	enabled?: boolean;
	checked?: boolean;
	onChange?: (val: boolean) => void;
	ariaLabel?: string;
}

export interface ICheckboxStyles {
	disabledCheckboxForeground?: Color;
}

export class Checkbox extends Widget {
	private _el: HTMLInputElement;
	private _label: HTMLSpanElement;
	private disabledCheckboxForeground?: Color;

	private _onChange = new Emitter<boolean>();
	public readonly onChange: Event<boolean> = this._onChange.event;

	constructor(container: HTMLElement, opts: ICheckboxOptions) {
		super();

		this._el = <input type='checkbox' style='vertical-align: middle'></input>;

		if (opts.ariaLabel) {
			this.ariaLabel = opts.ariaLabel;
		}

		this.onchange(this._el, e => {
			this._onChange.fire(this.checked);
		});

		this.onkeydown(this._el, e => {
			if (e.equals(KeyCode.Enter)) {
				this.checked = !this.checked;
				e.stopPropagation();
			}
		});

		this._label = <span style='vertical-align: middle'></span>;

		this.label = opts.label;
		this.enabled = opts.enabled || true;
		this.checked = opts.checked || false;

		if (opts.onChange) {
			this.onChange(opts.onChange);
		}

		container.appendChild(this._el);
		container.appendChild(this._label);
	}

	public set label(val: string) {
		this._label.innerText = val;
		// Default the aria label to the label if one wasn't specifically set by the user
		if (!this.ariaLabel) {
			this.ariaLabel = val;
		}
	}

	public set enabled(val: boolean) {
		this._el.disabled = !val;
		this.updateStyle();
	}

	public get enabled(): boolean {
		return !this._el.disabled;
	}

	public set checked(val: boolean) {
		this._el.checked = val;
	}

	public get checked(): boolean {
		return this._el.checked;
	}

	public set ariaLabel(val: string | null) {
		this._el.setAttribute('aria-label', val || '');
	}

	public get ariaLabel(): string | null {
		return this._el.getAttribute('aria-label');
	}

	public set required(val: boolean) {
		this._el.required = val;
	}

	public get required(): boolean {
		return this._el.required;
	}

	public focus(): void {
		this._el.focus();
	}

	public disable(): void {
		this.enabled = false;
	}

	public enable(): void {
		this.enabled = true;
	}

	public setHeight(value: string) {
		this._el.style.height = value;
	}

	public setWidth(value: string) {
		this._el.style.width = value;
	}

	public style(styles: ICheckboxStyles): void {
		this.disabledCheckboxForeground = styles.disabledCheckboxForeground;
		this.updateStyle();
	}

	private updateStyle(): void {
		this._label.style.color = !this.enabled && this.disabledCheckboxForeground ? this.disabledCheckboxForeground.toString() : 'inherit';
	}
}
